界面调整 Interface adjustment
Deardrops/webxoss-deckeditor2 pull request #25
Opened 2017-01-30 10:37 UTC by Deardrops

2017-01-30 11:26 UTC, webxoss commented on src/components/Cell.vue
> +      let typeClasses = type + '  ' + classes
用ES6字符模板吧

2017-01-30 11:26 UTC, webxoss commented on src/components/Cell.vue
> +    hasNoCost() {
`noCost`

`has` 是动词，要参数的函数才用`has`

2017-01-31 05:46 UTC, webxoss requested changes
关于 counter 删除行为的，revert 或者 reset 掉。
方案商量好再去实现。

尽量一个PR一个 feature。

2017-01-31 05:46 UTC, webxoss commented on src/components/DeckHead.vue
> +  line-height: calc(0.8 * var(--header-height));
诶诶诶？要一样高才好看啦

2017-01-31 05:46 UTC, webxoss commented on src/store.js
> +  shownPids: [],
不是这么玩的。。。

`query`是原子的，这个不是

2017-01-31 06:09 UTC, Deardrops commented
已reset

2017-01-31 06:59 UTC, webxoss approved these changes

2017-01-31 06:59 UTC, webxoss commented on src/components/Cell.vue
> +        return false // SIGNI / RESONA do not show " 0 cost"
注释有点长，放上面单独一行

2017-01-31 06:59 UTC, webxoss commented on src/components/Cell.vue
> +        return true
```
return !!this.costs.length
```

2017-01-31 06:59 UTC, webxoss commented on src/components/Cell.vue
> +@import 'css/colors.css';
这样复用会有重复代码
```
<style src="css/colors.css" module="$color"></style>

<template>
  <div :class="$color[card.color]"></div>
</template>
```
这样比较好

2017-01-31 06:59 UTC, webxoss commented on src/components/Counter.vue
> +
？

2017-01-31 07:36 UTC, webxoss commented on src/components/DeckHead.vue
> +  line-height: calc(0.8 * var(--header-height));
哦，也不一定哦，这个不是`bar`，就这样吧

2017-01-31 10:09 UTC, merged