load CardInfo language file by fetch
Deardrops/webxoss-deckeditor2 pull request #85
Opened 2017-05-10 05:20 UTC by Deardrops

2017-05-10 05:49 UTC, webxoss requested changes
换个优雅点的实现。
lang 要不要 gitignore 掉？

2017-05-10 05:49 UTC, webxoss commented on src/index.js
> +  console.error('Error in ImageFileCache.init():')
alert 是给用户看的。。

2017-05-10 05:49 UTC, webxoss commented on src/index.js
> +window.CardInfo_it = Object.create(window.CardInfo)
不要照抄那边的实现啊，这样可不优雅

2017-05-10 15:59 UTC, webxoss requested changes
~~看看为什么 ci 没过~~

2017-05-10 15:59 UTC, webxoss commented on src/js/CardInfoManager.js
> +export default function initCardInfos() {
这里 default 会很奇怪，文件名和 default 的导出不一致

2017-05-10 15:59 UTC, webxoss commented on src/js/CardInfoManager.js
> +window.CardInfo_it = Object.create(window.CardInfo)
尽量不要污染全局啊，这里有必要污染 window 吗？

2017-05-10 15:59 UTC, webxoss commented on src/js/CardInfoManager.js
> +  let dir = location.pathname.match(/\/next\/?$/) ? '../lang/' : './lang/'
用 `process.env.NODE_ENV`
见 webpack.config.js

2017-05-10 15:59 UTC, webxoss commented on src/js/CardInfoManager.js
> +          if (name === 'CardInfo_en') {
注释

2017-05-10 15:59 UTC, webxoss commented on src/js/Localize.js
> +  // return str + Localize.getMap().suffix
。。。直接不要 suff

2017-05-10 15:59 UTC, webxoss commented on src/js/CardInfoManager.js
> +export const setCardInfo = lang => {
命名。。。这名字谁看得出来是干嘛的啊

2017-05-11 06:31 UTC, webxoss reviewed
测一下，没问题就 rebase 和了吧

2017-05-11 07:26 UTC, Deardrops commented
@webxoss test passed, approve needed

2017-05-11 07:27 UTC, webxoss approved these changes

2017-05-11 07:27 UTC, merged